name: Build Flutter Mobile Apps (Unsigned)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS
        run: |
          # Build without codesigning
          flutter build ios --release --no-codesign
          
          # Build archive
          cd ios
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Package IPA
        run: |
          cd ios/build/Runner.xcarchive/Products/Applications
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app-release.ipa Payload
          
          # Create directory for artifact
          mkdir -p ../../../../../build/ios/ipa
          mv app-release.ipa ../../../../../build/ios/ipa/

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: ios/build/ios/ipa/app-release.ipa

      - name: List build directories (for debugging)
        if: always()
        run: |
          echo "iOS build directory contents:"
          ls -R ios/build/
