name: Build Flutter Mobile Apps (Unsigned)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA Directory
        run: |
          mkdir -p build/ios/ipa

      - name: Create Unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app-release.ipa Payload
          cp app-release.ipa ../../ipa/
          
      - name: Verify IPA
        run: |
          echo "Contents of build/ios directory:"
          ls -R build/ios
          echo "Contents of build/ios/ipa directory:"
          ls -R build/ios/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/ios/ipa/app-release.ipa

      - name: Upload Build Directory (if IPA creation fails)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ios-build-directory
          path: build/ios
