name: Build Flutter Mobile Apps (Unsigned)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  initialize-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Create and Initialize builds directory
        run: |
          mkdir -p builds
          touch builds/.gitkeep
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Commit builds directory
        run: |
          git add builds/.gitkeep
          git commit -m "Add builds directory [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    needs: initialize-builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Copy APK to builds directory
        run: |
          mkdir -p builds
          cp build/app/outputs/flutter-apk/app-release.apk builds/

      - name: Upload APK for iOS job
        uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: builds/app-release.apk

  build-ios:
    needs: build-android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Create Unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app-release.ipa Payload
          mkdir -p ../../../builds
          cp app-release.ipa ../../../builds/

      - name: Download Android Build
        uses: actions/download-artifact@v3
        with:
          name: android-build
          path: builds/

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and Push Builds
        run: |
          git add builds/
          git commit -m "Add latest builds [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload as Artifacts (Backup)
        uses: actions/upload-artifact@v3
        with:
          name: mobile-builds
          path: builds/
